version: 2

jobs:
  fmt:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Check formating
          command: terraform fmt --recursive -check=true

  validate:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run: terraform init
      - run:
          name: Validate files
          command: terraform validate

  tflint:
    docker:
      - image: wata727/tflint
    steps:
      - checkout
      - run:
          name: TFLint
          command: tflint


  terratest:
    docker:
      - image: web3f/terratest:v0.1.0
    steps:
      - checkout
      - run:
          description: Install dependencies
          command: |
            wget -O /usr/local/bin/aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.8/2020-04-16/bin/linux/amd64/aws-iam-authenticator
            chmod +x /usr/local/bin/aws-iam-authenticator
            wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
            chmod +x /usr/local/bin/kubectl
      - run:
          description: Integration tests
          command: |
            cd test
            go test -v -timeout 45m

workflows:
  version: 2
  test-module:
    jobs:
      - fmt
      - tflint
      - validate
      - terratest:
          requires:
            - fmt
            - tflint
            - validate
          filters:
            branches:
              only: /master/

